services:
  php:
    build: ./php
    container_name: php
    volumes:
      - ./app:/tags_parser
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      - PHP_IDE_CONFIG=serverName=tags_parser